#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : blinker
Version  : 1.4
Release  : 20
URL      : http://pypi.debian.net/blinker/blinker-1.4.tar.gz
Source0  : http://pypi.debian.net/blinker/blinker-1.4.tar.gz
Summary  : Fast, simple object-to-object and broadcast signaling
Group    : Development/Tools
License  : MIT
Requires: blinker-python3
Requires: blinker-license
Requires: blinker-python
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
# Blinker
        
        Blinker provides a fast dispatching system that allows any number of
        interested parties to subscribe to events, or "signals".
        
        Signal receivers can subscribe to specific senders or receive signals
        sent by any sender.
        
            >>> from blinker import signal
            >>> started = signal('round-started')

%package license
Summary: license components for the blinker package.
Group: Default

%description license
license components for the blinker package.


%package python
Summary: python components for the blinker package.
Group: Default
Requires: blinker-python3

%description python
python components for the blinker package.


%package python3
Summary: python3 components for the blinker package.
Group: Default
Requires: python3-core

%description python3
python3 components for the blinker package.


%prep
%setup -q -n blinker-1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532216751
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/blinker
cp LICENSE %{buildroot}/usr/share/doc/blinker/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/blinker/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
